services:
  postgres:
    image: postgres:17
    container_name: bankify-postgres
    environment:
      POSTGRES_DB: bankify
      POSTGRES_USER: bankify
      POSTGRES_PASSWORD: bankify
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  bankify:
    build: .
    container_name: bankify-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankify
      SPRING_DATASOURCE_USERNAME: bankify
      SPRING_DATASOURCE_PASSWORD: bankify
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  redis:
    image: redis:7
    container_name: bankify-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bankify-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: bankify
      RABBITMQ_DEFAULT_PASS: bankify
    ports:
      - "5672:5672" #AMQP
      - "15672:15672" #Management UI

volumes:
  postgres_data:
