
services:
  postgres:
    image: postgres:17
    container_name: bankify-postgres
    environment:
      POSTGRES_DB: bankify
      POSTGRES_USER: bankify
      POSTGRES_PASSWORD: bankify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: bankify-redis
    ports:
      - "6379:6479"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: bankify-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: bankify
      RABBITMQ_DEFAULT_PASS: bankify
    ports:
      - "5672:5672"        #AMQP
      - "15672:15672"       #Management UI

volumes:
  postgres_data:

