server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankify
    username: bankify
    password: bankify
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # for now, auto-create tables; change to validate in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: bankify
    password: bankify

  security:
    jwt:
      secret: "this-should-be-long-and-random-change-me-later-1234567890"
      expiration-seconds: 180

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
